name: Snyk Full Platform

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  SNYK_ORG: sampro

jobs:
  snyk-os:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - uses: snyk/actions/setup@master
        with:
          args: --org=${{ env.SNYK_ORG }}
      - name: Snyk OS Test
        run: |
          npm install snyk
          snyk test --org=${{ env.SNYK_ORG }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
      - name: Monitor dependencies for security issues with Snyk
        run: snyk monitor --org=${{ env.SNYK_ORG }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  snyk-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
        with:
          args: --org=${{ env.SNYK_ORG }}
      - name: Snyk Code Test
        continue-on-error: true
        run: snyk code test --org=${{ env.SNYK_ORG }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  snyk-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag boosef-juiceshop:latest
      - name: Scan Docker Vulnerabilities
        uses: snyk/actions/docker@master
        with:
          image: boosef-juiceshop:latest
          command: test
          args: --org=${{ env.SNYK_ORG }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Monitor Docker Vulnerabilities
        uses: snyk/actions/docker@master
        with:
          image: boosef-juiceshop:latest
          command: monitor
          args: --org=${{ env.SNYK_ORG }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  snyk-iac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run and monitor Snyk to check configuration files for security issues
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --report --org=${{ env.SNYK_ORG }}
